spring.application.name=demo1
spring.datasource.url=jdbc:mysql://localhost:3306/REVISION?createDatabaseIfNotExist=true
spring.datasource.username=root
server.port=8089
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update