spring.application.name=ApiGatewayWeb
server.port=8088

spring.config.import=optional:configserver:http://config-server:8888

eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://eureka:8761/eureka/

# Global CORS configuration (Handled in CorsConfig.java)
# spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:4200
# spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS,HEAD
# spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
# spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
# spring.cloud.gateway.globalcors.cors-configurations.[/**].max-age=3600

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.routes[0].id=ms_category
spring.cloud.gateway.routes[0].uri=lb://ms-category
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/categories/**

spring.cloud.gateway.routes[1].id=ms_order
spring.cloud.gateway.routes[1].uri=lb://ms-order
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**

spring.cloud.gateway.routes[2].id=ms_article
spring.cloud.gateway.routes[2].uri=lb://ms-article
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/articles/**

spring.cloud.gateway.routes[3].id=manage_users_auth
spring.cloud.gateway.routes[3].uri=lb://manage-users
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[4].id=manage_users_main
spring.cloud.gateway.routes[4].uri=lb://manage-users
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[5].id=ms_order_promos
spring.cloud.gateway.routes[5].uri=lb://ms-order
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/promos/**

spring.cloud.gateway.routes[6].id=ms_article_uploads
spring.cloud.gateway.routes[6].uri=lb://ms-article
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/articles/uploads/**

spring.cloud.gateway.routes[7].id=ms_feedback
spring.cloud.gateway.routes[7].uri=lb://ms-feedback
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/feedbacks/**