spring.application.name=MS_CATEGORY
server.port=8081

spring.datasource.url=jdbc:mysql://mysql:3306/ecommerce?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
eureka.instance.hostname=ms-category
eureka.client.service-url.defaultZone=http://eureka:8761/eureka/